name: karmic_canteen_app
description: A meal selection app for Karmic Solutions employees

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  csv: ^6.0.0
  share_plus: ^10.0.2 
  fl_chart: ^0.69.0
  mailer: ^6.0.1
  url_launcher: ^6.2.1
  easy_localization: ^3.0.7
  flutter_localizations:
    sdk: flutter

  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4 

  # State Management & Navigation
  provider: ^6.1.2
  go_router: ^14.6.1
  
  # UI
  google_fonts: ^6.2.1
  intl: ^0.19.0
  
  # Utilities
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/logo.jpeg

